### ISSUE TITLE
p2 repo doesn't work

### ISSUE THREAD

**Issue by martinlippert** [sidespin/m2e-chromatic#2]
I am using this p2 repo URL to install this feature from within a tycho product build, but it fails with:

```
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'm2e-chromatic' from location https://sidespin.github.io/m2e-chromatic/update/: Unable to read repository at https://sidespin.github.io/m2e-chromatic/update. Artifact not found: https://dl.bintray.com/sidespin/repo/m2e-chromatic/1.0.1/content.xml.xz. -> [Help 1]
```

Trying to show the repository content using the Oomph Repository Explorer produces the same exception.

Trying the repo from the `Install New Software` dialog within Eclipse works.

Any idea what might be going wrong here?

**Comment by fbricon** [comment]
Hi Martin, 

Bintray deleted the sidespin org, so no more update site available for now. 

I'll try to deploy to GH directly instead

**Comment by fbricon** [comment]
Should work now

**Comment by martinlippert** [comment]
Awesome, thanks so much for the super quick turnaround here. Much appreciated!!!
